name: canvaslite
services:
  backend:
    build: ./backend
    environment:
      PORT: 5000
      MONGO_URI: ${MONGO_URI:-mongodb://mongo:27017/canvaslite}
      JWT_SECRET: ${JWT_SECRET:-change-me-in-production}
    networks:
      - canvaslite
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    networks:
      - canvaslite
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-/api}
    depends_on:
      - backend
    networks:
      - canvaslite
      - coolify
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.canvaslite.entrypoints=http
      - traefik.http.routers.canvaslite.rule=Host(`canvaslite.192.168.1.101.nip.io`) || Host(`canvaslite.192.168.1.101.nip.io.sslip.io`) || Host(`djb7q5a918tfwq4omaodnx51.192.168.1.101.nip.io.sslip.io`)
      - traefik.http.routers.canvaslite.service=canvaslite
      - traefik.http.services.canvaslite.loadbalancer.server.port=80
      - coolify.managed=true
      - traefik.docker.network=coolify

volumes:
  mongo_data:

networks:
  canvaslite:
  coolify:
    external: true
    name: coolify
